<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesión</title>
</head>
<body>
    <a href="index.php">Volver</a>
    <h2>Iniciar Sesión</h2>
    <form action="index.php?c=user" method="POST">
        <input type="text" name="username" placeholder="Nombre de usuario" required>
        <br><br>
        <input type="password" name="password" placeholder="Contraseña" required>
        <br><br>
        <input type="submit" name="login" value="Iniciar Sesión">
    </form>
    <p>¿No tienes cuenta? <a href="index.php?register">Regístrate aquí</a></p>
</body>
</html>