<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Login</title>
</head>
<body>

<a href="index.php">volver</a><br>
    haz login:
    <form action="index.php?c=user" method="POST">
        <input type="text" name="name" placeholder="usuario">
        <input type="password" name="password" placeholder="contraseña">
        <input type="submit" name="login">
</form>
</body>
</html>