<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
    </head>
    <body>
        <form action="index.php?c=user" method="POST">
            <input type="text" name="username" placeholder="nombre de usuario">
            <input type="text" name="password" placeholder="contraseña">
            <input type="submit">
        </form>
    </body>
</html>