<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda Online</title>
</head>
<body>
    BIENVENIDOS A LA TIENDA
    <br><br>
    <?php
    if(isset($_SESSION['user'])){
        echo "hola ".$_SESSION['user']->getUsername().
        "<br><br>".
        "<a href='index.php?c=product&new'>Subir producto</a>".
        "<br><br>".
        "<a href='index.php?c=user&logout'>Salir</a>";
    }else {
    ?>
    <a href="index.php?login">Entrar</a> <a href="index.php?register">Registrar</a>
    <?php
    }
    echo "<br><br>";
    foreach($products as $product){
        echo $product->getDescription();
        echo "<span style='margin-left: 10px;'>";
        echo date("d/m/Y H:i", strtotime($product->getCreatedAt()));
        echo "</span>";
        echo "<br>";
    ?>
        <form action="index.php?c=order&add" method="POST">
            <input type="hidden" name="id" <?php echo 'value="'.$product->getId().'"'; ?>>
            <input type="number" name="quantity" value="1">
            <input type="submit" value="Añadir al carrito">
        </form>
    <?php
    }
    ?>
</body>
</html>