<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tienda Online</title>
    </head>
    <body>
        BIENVENIDOS A LA TIENDA
        <br><br>
        <?php
        if(isset($_SESSION['user'])){
            echo "BIENVENIDO " . $_SESSION['user']->getUsername();
            echo " &nbsp;&nbsp; ";
            echo "<br><br>";
            echo "<a href='index.php?c=product&new'>Subir producto</a>";
            echo " &nbsp;&nbsp; ";
            echo "<a href='index.php?c=user&logout'>Salir</a>";
        }else{
            echo "<a href='index.php?login'>Login</a>";
            echo " &nbsp;&nbsp;&nbsp; ";
            echo "<a href='index.php?register'>Registrarse</a>";
        }
        ?>
        <br><br>
        <?php
        foreach($products as $product){
            echo "<a href='index.php?c=product&id=".$product->getProductId()."'>";
            echo $product->getDescription();
            echo "</a><br>";
            echo $product->getPrice() . "<br>";
            echo $product->getStock() . "<br>";
        ?>
            <form action="index.php?c=order&add" method="POST">
                <input type="hidden" name="product_id" value="<?= $product->getProductId() ?>">
                <button type="submit">Añadir al carrito</button>
            </form>
        <?php
        }
        ?>
    </body>
</html>