<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="index.php?c=product&add" method="POST">
        <label for="description">descripción</label>
        <input type="text" id="description" name="description" required>
        <label for="price">precio</label>
        <input type="number" id="price" name="price" required>
        <label for="stock">stock</label>
        <input type="number" id="stock" name="stock" required>
        <button type="submit" name="add">añadir</button>
    </form>
    <br><br>
    <a href="index.php">Volver a la tienda</a>
</body>
</html>