<html><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo producto</title>
</head>
<body>
    <form action="index.php?c=product&add" method="POST">
        <input type="text" name="name" placeholder="nombre">
        <input type="text" name="price" placeholder="precio">
        <input type="text" name="stock" placeholder="stock">
        <input type="submit" value="Añadir">
    </form>
</body>
</html>