<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="index.php">volver</a>
    Registrate
        <form action="index.php" method="POST">
            <input type="text"  name="username" placeholder="usuario">
            <br>
            <input type="password" name="password">
            <br>
            <input type="submit">
        </form>
</body>
</html>