<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Registro</title>
</head>
<body>
    <a href="index.php">volver</a>
    <br><br>
    <form action="index.php?c=user" method="POST">
        <input type="text" name="username" placeholder="nombre de usuario">
        <input type="password" name="password" placeholder="contraseña">
        <input type="submit" name="register">
</form>
</body>
</html>