<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registrarse</title>
    </head>
    <body>
        <form action="index.php?c=user" method="POST">
            <label for="username">usuario</label>
            <input type="text" id="username" name="username" required>
            <label for="password">contraseña</label>
            <input type="password" id="password" name="password" required>
            <button type="submit" name="register">registrarse</button>
        </form>
        <br><br>
        <a href="index.php">Volver a la tienda</a>
    </body>
</html>