<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    este es tu pedido<br>

    <?php
echo "fecha: ".$order->getDate()."<br>";

foreach($order->getOrderLines() as $ol){
    echo $ol->getProduct()->getName(). " - ".$ol->getQuantity()." - ".$ol->getPrice()."<br>";
}

echo "total: ".$order->getTotal();


?>
</body>
</html>